// Mocks generated by Mockito 5.3.2 from annotations
// in com_nicodevelop_dotmessenger/test/services/notifications/initialize_notification_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:cloud_firestore/cloud_firestore.dart' as _i3;
import 'package:com_nicodevelop_dotmessenger/repositories/notification_repository.dart'
    as _i5;
import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:firebase_messaging/firebase_messaging.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseAuth_0 extends _i1.SmartFake implements _i2.FirebaseAuth {
  _FakeFirebaseAuth_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseFirestore_1 extends _i1.SmartFake
    implements _i3.FirebaseFirestore {
  _FakeFirebaseFirestore_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseMessaging_2 extends _i1.SmartFake
    implements _i4.FirebaseMessaging {
  _FakeFirebaseMessaging_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NotificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationRepository extends _i1.Mock
    implements _i5.NotificationRepository {
  @override
  _i2.FirebaseAuth get auth => (super.noSuchMethod(
        Invocation.getter(#auth),
        returnValue: _FakeFirebaseAuth_0(
          this,
          Invocation.getter(#auth),
        ),
        returnValueForMissingStub: _FakeFirebaseAuth_0(
          this,
          Invocation.getter(#auth),
        ),
      ) as _i2.FirebaseAuth);
  @override
  _i3.FirebaseFirestore get firebaseFirestore => (super.noSuchMethod(
        Invocation.getter(#firebaseFirestore),
        returnValue: _FakeFirebaseFirestore_1(
          this,
          Invocation.getter(#firebaseFirestore),
        ),
        returnValueForMissingStub: _FakeFirebaseFirestore_1(
          this,
          Invocation.getter(#firebaseFirestore),
        ),
      ) as _i3.FirebaseFirestore);
  @override
  _i4.FirebaseMessaging get messaging => (super.noSuchMethod(
        Invocation.getter(#messaging),
        returnValue: _FakeFirebaseMessaging_2(
          this,
          Invocation.getter(#messaging),
        ),
        returnValueForMissingStub: _FakeFirebaseMessaging_2(
          this,
          Invocation.getter(#messaging),
        ),
      ) as _i4.FirebaseMessaging);
  @override
  _i6.Stream<String> get onRefreshToken => (super.noSuchMethod(
        Invocation.getter(#onRefreshToken),
        returnValue: _i6.Stream<String>.empty(),
        returnValueForMissingStub: _i6.Stream<String>.empty(),
      ) as _i6.Stream<String>);
  @override
  _i6.Future<_i5.AuthorizationStatusEnum> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i6.Future<_i5.AuthorizationStatusEnum>.value(
            _i5.AuthorizationStatusEnum.authorized),
        returnValueForMissingStub:
            _i6.Future<_i5.AuthorizationStatusEnum>.value(
                _i5.AuthorizationStatusEnum.authorized),
      ) as _i6.Future<_i5.AuthorizationStatusEnum>);
  @override
  _i6.Future<void> saveToken() => (super.noSuchMethod(
        Invocation.method(
          #saveToken,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
