name: Build Web

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      firebaserc:
        required: true
      firebase_options:
        required: true
      firebase_token:
        required: true
  
jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.7'
          channel: 'stable'

      - name: Install firebase-tools
        run: npm install -g firebase-tools

      - name: Create firebase_options.dart file
        id: firebase_options
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: "firebase_options.dart"
          encodedString: ${{ secrets.firebase_options }}

      - name: Move firebase_options.dart to lib folder
        run: |
          mv ${{ steps.firebase_options.outputs.filePath }} lib

      - name: Create .firebaserc file
        id: firebaserc
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: ".firebaserc"
          encodedString: ${{ secrets.firebaserc }}

      - name: Move .env firebaserc to server
        run: |
          mv ${{ steps.firebaserc.outputs.filePath }} server/.firebaserc

      - name: Flutter import dependencies
        run: flutter pub get

      - name: Flutter build
        run: flutter build web

      - name: Move build to server
        run: |
          mv build/web ${{ inputs.config-path }}

      - name: Deploy web
        run: |
          cd server
          firebase deploy --only functions --token ${{ secrets.firebase_token }}