name: Quality checks

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  testing-web:
    uses: bynicodevelop/com_nicodevelop_dot_messenger/.github/workflows/tests.yaml@main
