name: Deploy

on:
  push:

jobs:
  # build:
  #   uses: bynicodevelop/com_nicodevelop_dot_messenger/.github/workflows/tests.yaml@develop

  deploy-server:
    # needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: $/.npm
          key: $-node-$
          restore-keys: $-node-

      - name: Install dependencies
        run: npm --prefix server/functions ci