name: Deploy

on:
  push:

jobs:
  testing:
    uses: bynicodevelop/com_nicodevelop_dot_messenger/.github/workflows/tests.yaml@develop

  build-server:
    uses: bynicodevelop/com_nicodevelop_dot_messenger/.github/workflows/build-server.yaml@develop

  build-web:
    uses: bynicodevelop/com_nicodevelop_dot_messenger/.github/workflows/build-web.yaml@develop

  deploy-server:
    # needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy serveur
        run: |
          cd server
          firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy client
        run: |
          cd server
          firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }}

      