name: Deploy

on:
  push:

jobs:
  testing:
    uses: bynicodevelop/com_nicodevelop_dot_messenger/.github/workflows/tests.yaml@develop

  build-server:
    uses: bynicodevelop/com_nicodevelop_dot_messenger/.github/workflows/build-server.yaml@develop
    secrets:
      env: ${{ secrets.ENV }}
      firebaserc: ${{ secrets.FIREBASERC }}
      firebase_token: ${{ secrets.FIREBASE_TOKEN }}

  build-web:
    needs: [testing, deploy-server]
    uses: bynicodevelop/com_nicodevelop_dot_messenger/.github/workflows/build-web.yaml@develop
    with:
      config-path: 'server/build/web'
    secrets:
      firebase_options: ${{ secrets.FIREBASE_OPTIONS }}
      firebase_token: ${{ secrets.FIREBASE_TOKEN }}