name: Deploy

on:
  push:

jobs:
  testing:
    uses: bynicodevelop/com_nicodevelop_dot_messenger/.github/workflows/tests.yaml@develop

  build-server:
    uses: bynicodevelop/com_nicodevelop_dot_messenger/.github/workflows/build-server.yaml@develop
    secrets:
      env: ${{ secrets.ENV }}
      firebaserc: ${{ secrets.FIREBASERC }}

  build-web:
    needs: [testing]
    uses: bynicodevelop/com_nicodevelop_dot_messenger/.github/workflows/build-web.yaml@develop
    with:
      config-path: 'server/build/web'
    secrets:
      firebase_options: ${{ secrets.FIREBASE_OPTIONS }}

  deploy-server:
    needs: [build-server]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy serveur
        run: |
          cd server
          firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }}

  deploy-web:
    needs: [deploy-server, build-web]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy web
        run: |
          cd server
          firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }}